export const INTEGRATIONS = [
  {
    slug: 'stripe',
    name: 'Stripe',
    badge: 'ST',
    color: '635bff',
    category: 'Payments',
    description: 'Sync successful payments, failed charges, and customer lifecycle signals.',
    useCase: 'Revenue events for sales and support automations',
    link: '/get-started?integration=stripe',
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    badge: 'PP',
    color: '00457c',
    category: 'Payments',
    description: 'Capture transaction status and trigger follow-up workflows instantly.',
    useCase: 'Payment confirmations and dispute workflow routing',
    link: '/get-started?integration=paypal',
  },
  {
    slug: 'google-analytics',
    name: 'Google Analytics',
    badge: 'GA',
    color: 'e37400',
    category: 'Analytics',
    description: 'Use traffic and behavior signals to qualify leads with better context.',
    useCase: 'Intent enrichment from session and conversion data',
    link: '/get-started?integration=google-analytics',
  },
  {
    slug: 'google-maps',
    name: 'Google Maps',
    badge: 'GM',
    color: '4285f4',
    category: 'Operations',
    description: 'Resolve location queries and route service requests automatically.',
    useCase: 'Location-aware support and logistics workflows',
    link: '/get-started?integration=google-maps',
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    badge: 'MC',
    color: 'ffe01b',
    category: 'Marketing',
    description: 'Trigger segmented nurture sequences from AI-qualified conversations.',
    useCase: 'Lead nurture and campaign-trigger automations',
    link: '/get-started?integration=mailchimp',
  },
  {
    slug: 'calendly',
    name: 'Calendly',
    badge: 'CA',
    color: '006bff',
    category: 'Scheduling',
    description: 'Book demos directly from chat or voice with calendar availability checks.',
    useCase: 'Auto-booking for qualified inbound opportunities',
    link: '/get-started?integration=calendly',
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    badge: 'TW',
    color: 'f22f46',
    category: 'Communication',
    description: 'Orchestrate voice and SMS journeys for outbound and support use cases.',
    useCase: 'Voice bots, SMS reminders, and fallback alerts',
    link: '/get-started?integration=twilio',
  },
  {
    slug: 'slack',
    name: 'Slack',
    badge: 'SL',
    color: '4a154b',
    category: 'Collaboration',
    description: 'Notify teams with transcripts, approvals, and escalation threads in-channel.',
    useCase: 'Human handoff alerts and ops coordination',
    link: '/get-started?integration=slack',
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    badge: 'ZD',
    color: '03363d',
    category: 'Support',
    description: 'Create and enrich tickets using full customer context from AI sessions.',
    useCase: 'Ticket deflection with structured escalation',
    link: '/get-started?integration=zendesk',
  },
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    badge: 'WA',
    color: '25d366',
    category: 'Communication',
    description: 'Run always-on customer conversations where your buyers already are.',
    useCase: 'Lead capture, order updates, and support messaging',
    link: '/get-started?integration=whatsapp',
  },
  {
    slug: 'firebase',
    name: 'Firebase',
    badge: 'FB',
    color: 'ffca28',
    category: 'Data',
    description: 'Sync app events and auth actions to drive contextual AI workflows.',
    useCase: 'Realtime product-event triggers and notifications',
    link: '/get-started?integration=firebase',
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    badge: 'HS',
    color: 'ff7a59',
    category: 'CRM',
    description: 'Keep contact records, deal stages, and activity timelines fully updated.',
    useCase: 'CRM updates and lifecycle stage progression',
    link: '/get-started?integration=hubspot',
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    badge: 'SF',
    color: '00a1e0',
    category: 'CRM',
    description: 'Sync leads, opportunities, and tasks from every AI-qualified conversation.',
    useCase: 'Sales Cloud updates and pipeline hygiene',
    link: '/get-started?integration=salesforce',
  },
  {
    slug: 'zoho',
    name: 'Zoho CRM',
    badge: 'ZO',
    color: 'c8202b',
    category: 'CRM',
    description: 'Route deals, notes, and follow-ups without manual CRM housekeeping.',
    useCase: 'Mid-market CRM automation and handoffs',
    link: '/get-started?integration=zoho',
  },
  {
    slug: 'shopify',
    name: 'Shopify',
    badge: 'SH',
    color: '95bf47',
    category: 'Commerce',
    description: 'Automate order-status and post-purchase support conversations.',
    useCase: 'Order support, upsell prompts, and customer retention',
    link: '/get-started?integration=shopify',
  },
  {
    slug: 'zapier',
    name: 'Zapier',
    badge: 'ZA',
    color: 'ff4f00',
    category: 'Automation',
    description: 'Connect AI outcomes into thousands of downstream business automations.',
    useCase: 'No-code orchestration across internal tools',
    link: '/get-started?integration=zapier',
  },
]
